name: ci

on:
  pull_request:

jobs:
  # Build job
  check_pr_builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          cache: "pnpm"
      - name: Build docs
        run: |
          pnpm ci
          pnpm run format:check
          pnpm docs:build
